### ISSUE TITLE
Password error

### ISSUE THREAD

**Issue by randoms** [mengzhuo/hikey970-ubuntu-image#3]
The password seems to be hikey970 instead of hikey.

**Comment by mengzhuo** [comment]
Oh, I've forgot to change readme

the code is here.
https://github.com/mengzhuo/hikey970-ubuntu-image/blob/master/rootfs/root/init.sh#L6

**Comment by jainrahul1** [comment]
@randoms how you are login to board, I believe HDMI port is not working so how to see ubuntu terminal to login?

**Comment by randoms** [comment]
![img](http://community.bwbot.org/assets/uploads/files/1526694480420-b9441cfc-3dac-4973-87c9-077fc78e70ef-image.png)

Plug in your USB cable to the left interface, and you will find a new tty device in your /dev folder, say ttyUSB0. Use screen command to view output of the board.

```
screen /dev/ttyUSB0 115200
```

Or plug in the internet cable, and use ssh to login the borad.

**Comment by jainrahul1** [comment]
Thanks a lot for your help, i did not know that it provide tty interface. I can now see the logs.
