### ISSUE TITLE
onboard wire network driver don't work

### ISSUE THREAD

**Issue by xlazom00** [mengzhuo/hikey970-ubuntu-image#5]
onboard wire network driver don't work.

**Comment by mengzhuo** [comment]
Try to plugin the ethernet cable and reboot.
Seems to be network-manager's configuration issue.

**Comment by xlazom00** [comment]
hi@hikey970:~$ lspci
00:00.0 PCI bridge: Huawei Technologies Co., Ltd. Device 3670 (rev 01)

**Comment by mengzhuo** [comment]
Have you tried `netplan generate` and `netplan apply` ?

Here is mine lspci
```
00:00.0 PCI bridge: Huawei Technologies Co., Ltd. Device 3670 (rev 01)
01:00.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:01.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:04.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:05.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:07.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:09.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
06:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 07)
```

**Comment by xlazom00** [comment]
so it looks like some problem with my board :(

**Comment by xlazom00** [comment]
It is also wired that when I power board from 5V power supply I can see 
lspci
00:00.0 PCI bridge: Huawei Technologies Co., Ltd. Device 3670 (rev 01)

but when I power board from 12V I don't get any output from lspci :)

**Comment by mengzhuo** [comment]
Hikey970 needs 12V/2A to run.
p.s. Can you find this in your `dmesg` ?
```hikey970 ~ # dmesg | grep Ether
[    1.070093] igb: Intel(R) Gigabit Ethernet Network Driver - version 5.4.0-k
[    1.070250] r8168 Gigabit Ethernet driver 8.045.08 loaded
```

**Comment by xlazom00** [comment]
[    1.070217] r8168 Gigabit Ethernet driver 8.045.08 loaded
[    1.070278] r8168 0000:06:00.0: enabling device (0000 -> 0002)
[    1.092306] r8168: This product is covered by one or more of the following patents: US6,570,884, US6,115,776, and US6,327,625.
[    1.092316] r8168  Copyright (C) 2017  Realtek NIC software team <nicfae@realtek.com>
                This program comes with ABSOLUTELY NO WARRANTY; for details, please see <http://www.gnu.org/licenses/>.
                This is free software, and you are welcome to redistribute it under certain conditions; see <http://www.gnu.org/licenses/>.
[    3.213293] r8168 0000:06:00.0 enp6s0: renamed from eth0
[    4.065668] IPv6: ADDRCONF(NETDEV_UP): enp6s0: link is not ready
[    4.068961] enp6s0: 0xffff000009ae2000, 50:1d:93:04:2b:b5, IRQ 327
[    4.302963] IPv6: ADDRCONF(NETDEV_UP): enp6s0: link is not ready

**Comment by xlazom00** [comment]
but I don't understand why it isn't visible in ifconfig -a

**Comment by xlazom00** [comment]
I don't understand but it is working now :)
couple restarts and it is working fine


And now
lspci
00:00.0 PCI bridge: Huawei Technologies Co., Ltd. Device 3670 (rev 01)
01:00.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:01.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:04.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:05.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:07.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
02:09.0 PCI bridge: PLX Technology, Inc. PEX 8606 6 Lane, 6 Port PCI Express Gen 2 (5.0 GT/s) Switch (rev ba)
06:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 07)

I don't understand :(
